#spring.application.name=StudentManagementSystem
#
#spring.datasource.url=jdbc:mysql://localhost:3306/RealCrudOnStudent?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=root
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true





spring.application.name=StudentManagementSystem

spring.datasource.url=jdbc:postgresql://dpg-d6u313npm1nc73cvi530-a:5432/student_db_lrcg
spring.datasource.username=student_db_lrcg_user
spring.datasource.password=zDxnsAx9PBJKxv8QnoakUbFSwzxqBk0y

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}